import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/compliance_report.dart';
import '../models/field_result.dart';

class PdfExporter {
  Future<void> exportAndShare(ComplianceReport report) async {
    final pdf = pw.Document();

    final scoreColor = report.overallScore >= 0.9
        ? PdfColors.green
        : report.overallScore >= 0.6
            ? PdfColors.orange
            : PdfColors.red;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Header
            pw.Text('MetriScan Compliance Report',
                style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.Text('Scan ID: ${report.scanId}', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
            pw.Text('Date: ${report.timestamp.toLocal().toString().substring(0, 16)}', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
            pw.SizedBox(height: 24),

            // Score
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: scoreColor, width: 2),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              ),
              child: pw.Row(
                children: [
                  pw.Text(
                    '${(report.overallScore * 100).toStringAsFixed(0)}%',
                    style: pw.TextStyle(fontSize: 32, fontWeight: pw.FontWeight.bold, color: scoreColor),
                  ),
                  pw.SizedBox(width: 16),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(report.statusLabel, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: scoreColor)),
                      pw.Text('${report.mandatoryFound} of ${report.mandatoryTotal} mandatory fields detected'),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 24),

            // Violations
            if (report.violations.isNotEmpty) ...[
              pw.Text('Violations', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.red800)),
              pw.SizedBox(height: 8),
              ...report.violations.map((v) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 4),
                child: pw.Row(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('• ', style: pw.TextStyle(color: PdfColors.red, fontWeight: pw.FontWeight.bold)),
                    pw.Expanded(child: pw.Text(v, style: pw.TextStyle(color: PdfColors.red800, fontSize: 12))),
                  ],
                ),
              )),
              pw.SizedBox(height: 24),
            ],

            // Details
            pw.Text('Extracted Fields', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 12),
            pw.TableHelper.fromTextArray(
              context: context,
              headers: ['Field', 'Status', 'Value / Notes'],
              data: report.fieldResults.map((r) {
                String notes = r.matchedText ?? r.normalisedValue ?? r.violation ?? 'Not found';
                if (r.fontSizePx != null) {
                  notes += '\n[Font Size: ${r.fontSizePx!.toStringAsFixed(1)}px]';
                }
                if (r.matchType != MatchType.coLocated) {
                  notes += '\n[Inferred via ${r.matchType.name}]';
                }
                return [
                  r.fieldLabel,
                  r.status.isPass ? 'Pass' : r.status.isFail ? 'Fail' : 'Partial',
                  notes,
                ];
              }).toList(),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
              rowDecoration: const pw.BoxDecoration(
                border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5)),
              ),
              cellAlignment: pw.Alignment.centerLeft,
            ),
            
            pw.SizedBox(height: 24),
            pw.Text(
              'Note: This report is generated by an automated system and does not constitute legally binding certified measurements. '
              'Font sizes and extraction accuracy are estimates.',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          ];
        },
      ),
    );

    final outputDir = await getApplicationDocumentsDirectory();
    final file = File('${outputDir.path}/metriscan_report_${report.scanId}.pdf');
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      subject: 'MetriScan Report - ${report.scanId}',
    );
  }
}
